[book]
authors = ["Tulir Asokan"]
language = "en"
multilingual = false
src = "."
title = "mautrix-bridges"
site-url = "/bridges/"

[build]
build-dir = "../dist/bridges"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/mautrix/docs"
git-repository-icon = "fa-github"
additional-js = ["./bridge-selector.js", "./additional.js"]
additional-css = ["additional.css"]
theme = "../theme/bridges"

[output.html.redirect]
"/go/imessage/setup.html" = "./mac/setup.html"
"/go/whatsapp/relaybot.html" = "../../general/relay-mode.html"
"/python/signal/relay-mode.html" = "../../general/relay-mode.html"
"/go/whatsapp/setup/index.html" = "../../setup.html?bridge=whatsapp"
"/go/whatsapp/setup/systemd.html" = "../../setup.html?bridge=whatsapp#systemd-service"
"/go/whatsapp/setup/docker.html" = "../../../general/docker-setup.html?bridge=whatsapp"
"/python/setup/docker.html" = "../../general/docker-setup.html"
"/python/setup/systemd.html" = "../setup.html#systemd-service"
"/python/setup/index.html" = "../setup.html"
"/python/signal/index.html" = "../../go/signal/index.html"
"/python/signal/authentication.html" = "../../go/signal/authentication.html"
"/python/signal/docker-setup.html" = "../../general/docker-setup.html?bridge=signal"
"/python/twitter/index.html" = "../../go/twitter/index.html"
"/python/twitter/authentication.html" = "../../go/twitter/authentication.html"
"/python/telegram/index.html" = "../../go/telegram/index.html"
"/python/telegram/authentication.html" = "../../go/telegram/authentication.html"
"/python/telegram/creating-and-managing-chats.html" = "https://github.com/mautrix/docs/blob/95395dff46e6468750c1625cbb741c866f0d98a2/bridges/python/telegram/creating-and-managing-chats.md"
"/python/telegram/management-commands.html" = "https://github.com/mautrix/docs/blob/95395dff46e6468750c1625cbb741c866f0d98a2/bridges/python/telegram/management-commands.md"
"/python/telegram/relay-bot.html" = "../../general/relay-mode.html"
"/python/telegram/provisioning-api.html" = "https://spec.mau.fi/megabridge/"
"/python/telegram/migrating-from-telematrix.html" = "https://github.com/mautrix/docs/blob/95395dff46e6468750c1625cbb741c866f0d98a2/bridges/python/telegram/migrating-from-telematrix.md"
"/python/telegram/dbms-migration.html" = "https://github.com/mautrix/docs/blob/95395dff46e6468750c1625cbb741c866f0d98a2/bridges/python/telegram/dbms-migration.md"

[output.linkcheck]
optional = true
user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
cache-timeout = 604800
exclude = [ 'developer\.android\.com' ]
traverse-parent-directories = false
